# Generated by Django 5.1.4 on 2025-01-13 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Module",
            new_name="Topic",
        ),
    ]
