# Generated by Django 5.1.4 on 2025-02-13 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_rename_module_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
