version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env