[tool.black]
line-length = 88
exclude = '''
/(
    env|venv  # Exclude the env and venv folders
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = [
    "env",  # Exclude the env folder
    "venv"  # Exclude the venv folder
]
