# Generated by Django 5.1.4 on 2025-03-30 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_userprofile_address_userprofile_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="course",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="enrollment_date",
        ),
    ]
