# Generated by Django 5.1.4 on 2025-02-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playgroundtask",
            name="input_image",
            field=models.ImageField(blank=True, null=True, upload_to="doodles/"),
        ),
    ]
