# Generated by Django 5.1.4 on 2025-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0002_playgroundtask_input_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playgroundtask",
            name="celery_task_id",
        ),
        migrations.AlterField(
            model_name="playgroundtask",
            name="status",
            field=models.CharField(
                choices=[("COMPLETED", "Completed"), ("FAILED", "Failed")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
