# Generated by Django 5.1.4 on 2025-01-12 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.topic"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("user", "topic", "question")},
        ),
    ]
