# Generated by Django 5.1.4 on 2025-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_alter_useranswer_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="description",
            field=models.CharField(default="No description provided.", max_length=1000),
        ),
        migrations.AddField(
            model_name="topic",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Easy", "Easy"),
                    ("Medium", "Medium"),
                    ("Hard", "Hard"),
                    ("Veteran", "Veteran"),
                ],
                default="Easy",
                help_text="Difficulty levels",
                max_length=7,
            ),
        ),
    ]
