# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - master  # Adjust based on your default branch

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

#       - name: Build Docker Image
#         run: docker build -t priyanshubatham/algolyzer:latest .

#       - name: Push Docker Image to Docker Hub
#         run: docker push priyanshubatham/algolyzer:latest